version: "3"
services:
  api:
    build: .
    ports:
      - "15000:5000"
    container_name: github-lens-api
    volumes:
      - ./app:/app
    environment:
      ENV: local
      FLASK_APP: api/main
    command: flask run --host=0.0.0.0 --debugger --reload
