version: "3"
services:
  api:
    image: node:16
    ports:
      - "5050:3000"
    volumes:
      - .:/app
    tty: true
    working_dir: /app
    command: yarn start
    networks:
      - github_lens_nw
    depends_on:
      - db

  db:
    image: mysql:latest
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: github_lens
      MYSQL_USER: github_lens_user
      MYSQL_PASSWORD: github_lens_password
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - "33066:3306"
    networks:
      - github_lens_nw

networks:
  github_lens_nw: